server:
  port: 8084

spring:
  datasource:
    # Admin service might not need its own DB if it only orchestrates, 
    # but usually it needs one for audit logs or specific admin data.
    # For now, we assume it orchestrates or uses a small DB.
    url: jdbc:mysql://localhost:3306/e_voting_admin_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
