server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_voting_voter_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Service URL for OCR (Direct internal communication or via Gateway/Feign)
application:
  config:
    ocr-service-url: http://ocr-service
